
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URL;
import java.util.regex.Pattern;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author michał
 */
public class Aplikacja extends javax.swing.JFrame {

    /**
     * Creates new form Aplikacja
     */
    public Aplikacja() {
        initComponents();
        initDemo();
        
    }

    /**
     * This meth+od is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tekst = new javax.swing.JPanel();
        edytor = new javax.swing.JPanel();
        numer1 = new javax.swing.JLabel();
        L1 = new javax.swing.JScrollPane();
        zamieńCel = new javax.swing.JTextArea();
        zamieńKlik = new javax.swing.JButton();
        P1 = new javax.swing.JScrollPane();
        zamieńZamiennik = new javax.swing.JTextArea();
        numer2 = new javax.swing.JLabel();
        L2 = new javax.swing.JScrollPane();
        wstawCel = new javax.swing.JTextArea();
        wstawKlik = new javax.swing.JToggleButton();
        wstawIndywidualnie = new javax.swing.JRadioButton();
        wstawOffset = new javax.swing.JTextField();
        wstawPrzed = new javax.swing.JRadioButton();
        wstawPo = new javax.swing.JRadioButton();
        P2 = new javax.swing.JScrollPane();
        wstawWstawka = new javax.swing.JTextArea();
        L3 = new javax.swing.JScrollPane();
        cięcieCel = new javax.swing.JTextArea();
        wyodrębnijKlik = new javax.swing.JButton();
        usuńKlik = new javax.swing.JButton();
        wyodrębnij_NieaktywnyTekst = new javax.swing.JTextField();
        P3 = new javax.swing.JScrollPane();
        cięcieUsuń = new javax.swing.JTextArea();
        L4 = new javax.swing.JScrollPane();
        podstawCel = new javax.swing.JTextArea();
        podstawKlik = new javax.swing.JButton();
        _4 = new javax.swing.JScrollPane();
        podstawZmienne = new javax.swing.JTextArea();
        P4 = new javax.swing.JScrollPane();
        podstawWzór = new javax.swing.JTextArea();
        inf = new javax.swing.JScrollPane();
        info = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        numer3 = new javax.swing.JLabel();
        numer4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        we = new javax.swing.JScrollPane();
        wejście = new javax.swing.JTextArea();
        wGórę = new javax.swing.JButton();
        _cofnij = new javax.swing.JButton();
        wy = new javax.swing.JScrollPane();
        wyjście = new javax.swing.JTextArea();
        zasoby = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        adresStrony = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        zasobyWczytaj = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        buttonGroup2.add(wstawPrzed);
        buttonGroup2.add(wstawPo);
        buttonGroup2.add(wstawIndywidualnie);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel2.setText("sesja");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nazwa 1", "nazwa 2", "nazwa 3", "nazwa 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jComboBox1, 0, 179, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(311, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setPreferredSize(new java.awt.Dimension(193, 358));

        jLabel4.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel4.setText("praca");

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jButton1.setText("ZAKOŃCZ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tekst.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        numer1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numer1.setText("1");

        L1.setMaximumSize(new java.awt.Dimension(111, 66));
        L1.setMinimumSize(new java.awt.Dimension(111, 66));
        L1.setPreferredSize(new java.awt.Dimension(111, 66));

        zamieńCel.setColumns(8);
        zamieńCel.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        zamieńCel.setRows(4);
        L1.setViewportView(zamieńCel);

        zamieńKlik.setText("zamień na");
        zamieńKlik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zamieńKlikActionPerformed(evt);
            }
        });

        P1.setMaximumSize(new java.awt.Dimension(111, 66));
        P1.setMinimumSize(new java.awt.Dimension(111, 66));
        P1.setPreferredSize(new java.awt.Dimension(111, 66));

        zamieńZamiennik.setColumns(8);
        zamieńZamiennik.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        zamieńZamiennik.setRows(4);
        P1.setViewportView(zamieńZamiennik);

        numer2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numer2.setText("2");

        L2.setMaximumSize(new java.awt.Dimension(111, 66));
        L2.setMinimumSize(new java.awt.Dimension(111, 66));
        L2.setPreferredSize(new java.awt.Dimension(111, 66));

        wstawCel.setColumns(8);
        wstawCel.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        wstawCel.setRows(4);
        L2.setViewportView(wstawCel);

        wstawKlik.setText("wstaw");
        wstawKlik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wstawKlikActionPerformed(evt);
            }
        });

        wstawIndywidualnie.setText("w indeksie");
        wstawIndywidualnie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wstawIndywidualnieActionPerformed(evt);
            }
        });

        wstawOffset.setEditable(false);
        wstawOffset.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        wstawOffset.setText("-0");
        wstawOffset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wstawOffsetActionPerformed(evt);
            }
        });

        wstawPrzed.setText("przed...");
        wstawPrzed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wstawPrzedActionPerformed(evt);
            }
        });

        wstawPo.setText(" po...");
        wstawPo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wstawPoActionPerformed(evt);
            }
        });

        P2.setMaximumSize(new java.awt.Dimension(111, 66));
        P2.setMinimumSize(new java.awt.Dimension(111, 66));
        P2.setPreferredSize(new java.awt.Dimension(111, 66));

        wstawWstawka.setColumns(8);
        wstawWstawka.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        wstawWstawka.setRows(4);
        P2.setViewportView(wstawWstawka);

        L3.setMaximumSize(new java.awt.Dimension(111, 66));
        L3.setMinimumSize(new java.awt.Dimension(111, 66));
        L3.setPreferredSize(new java.awt.Dimension(111, 66));

        cięcieCel.setColumns(8);
        cięcieCel.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        cięcieCel.setRows(4);
        cięcieCel.setEnabled(false);
        L3.setViewportView(cięcieCel);

        wyodrębnijKlik.setText("wyodębnij");
        wyodrębnijKlik.setEnabled(false);
        wyodrębnijKlik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wyodrębnijKlikActionPerformed(evt);
            }
        });

        usuńKlik.setText("usuń");
        usuńKlik.setEnabled(false);
        usuńKlik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuńKlikActionPerformed(evt);
            }
        });

        wyodrębnij_NieaktywnyTekst.setText("funkcja nieaktywna(pole edycji)");
        wyodrębnij_NieaktywnyTekst.setEnabled(false);

        P3.setMaximumSize(new java.awt.Dimension(111, 66));
        P3.setMinimumSize(new java.awt.Dimension(111, 66));
        P3.setPreferredSize(new java.awt.Dimension(111, 66));

        cięcieUsuń.setColumns(8);
        cięcieUsuń.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        cięcieUsuń.setRows(4);
        cięcieUsuń.setEnabled(false);
        P3.setViewportView(cięcieUsuń);

        L4.setMaximumSize(new java.awt.Dimension(111, 66));
        L4.setMinimumSize(new java.awt.Dimension(111, 66));
        L4.setPreferredSize(new java.awt.Dimension(111, 66));

        podstawCel.setColumns(8);
        podstawCel.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        podstawCel.setRows(4);
        L4.setViewportView(podstawCel);

        podstawKlik.setText("podstaw");
        podstawKlik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                podstawKlikActionPerformed(evt);
            }
        });

        _4.setMaximumSize(new java.awt.Dimension(111, 66));
        _4.setMinimumSize(new java.awt.Dimension(111, 66));
        _4.setPreferredSize(new java.awt.Dimension(111, 66));

        podstawZmienne.setColumns(8);
        podstawZmienne.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        podstawZmienne.setRows(4);
        _4.setViewportView(podstawZmienne);

        P4.setMaximumSize(new java.awt.Dimension(111, 66));
        P4.setMinimumSize(new java.awt.Dimension(111, 66));
        P4.setPreferredSize(new java.awt.Dimension(111, 66));

        podstawWzór.setColumns(8);
        podstawWzór.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        podstawWzór.setRows(4);
        P4.setViewportView(podstawWzór);

        info.setEditable(false);
        info.setColumns(20);
        info.setRows(5);
        inf.setViewportView(info);

        jButton5.setBackground(new java.awt.Color(51, 153, 255));
        jButton5.setForeground(new java.awt.Color(0, 255, 255));
        jButton5.setText("kaskada");
        jButton5.setBorderPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        numer3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numer3.setText("3");

        numer4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numer4.setText("4");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout edytorLayout = new javax.swing.GroupLayout(edytor);
        edytor.setLayout(edytorLayout);
        edytorLayout.setHorizontalGroup(
            edytorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edytorLayout.createSequentialGroup()
                .addGroup(edytorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(numer1)
                    .addComponent(numer2)
                    .addComponent(numer3)
                    .addComponent(numer4))
                .addGap(0, 0, 0)
                .addGroup(edytorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inf)
                    .addGroup(edytorLayout.createSequentialGroup()
                        .addGroup(edytorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(edytorLayout.createSequentialGroup()
                                .addGroup(edytorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(L4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(L3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(L2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(L1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(edytorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(edytorLayout.createSequentialGroup()
                                        .addGroup(edytorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(wstawPrzed, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(wstawPo, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(wstawIndywidualnie, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(0, 0, 0)
                                        .addComponent(wstawOffset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(wstawKlik))
                                    .addComponent(wyodrębnij_NieaktywnyTekst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(edytorLayout.createSequentialGroup()
                                        .addGap(0, 0, 0)
                                        .addGroup(edytorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(edytorLayout.createSequentialGroup()
                                                .addComponent(wyodrębnijKlik)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(usuńKlik))
                                            .addComponent(zamieńKlik)
                                            .addGroup(edytorLayout.createSequentialGroup()
                                                .addComponent(_4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, 0)
                                                .addComponent(podstawKlik))))))
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(edytorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5)
                            .addGroup(edytorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(P4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(P3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(P1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(P2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        edytorLayout.setVerticalGroup(
            edytorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edytorLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(edytorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zamieńKlik)
                    .addComponent(numer1))
                .addGroup(edytorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numer2)
                    .addComponent(P2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(edytorLayout.createSequentialGroup()
                        .addComponent(wstawPrzed, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addGroup(edytorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(wstawIndywidualnie, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wstawOffset, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wstawKlik, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(wstawPo, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(L2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(edytorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numer3)
                    .addComponent(P3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(edytorLayout.createSequentialGroup()
                        .addGroup(edytorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usuńKlik)
                            .addComponent(wyodrębnijKlik))
                        .addGap(20, 20, 20)
                        .addComponent(wyodrębnij_NieaktywnyTekst, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(edytorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(podstawKlik)
                    .addComponent(numer4)
                    .addComponent(L4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(edytorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(inf, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                .addContainerGap())
        );

        wejście.setColumns(20);
        wejście.setRows(5);
        we.setViewportView(wejście);

        wGórę.setText("zamień");
        wGórę.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wGóręActionPerformed(evt);
            }
        });

        _cofnij.setText("cofnij");
        _cofnij.setEnabled(false);

        wyjście.setColumns(20);
        wyjście.setRows(5);
        wy.setViewportView(wyjście);

        javax.swing.GroupLayout tekstLayout = new javax.swing.GroupLayout(tekst);
        tekst.setLayout(tekstLayout);
        tekstLayout.setHorizontalGroup(
            tekstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tekstLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(edytor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tekstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tekstLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(wGórę)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(_cofnij)
                        .addContainerGap(293, Short.MAX_VALUE))
                    .addComponent(wy)
                    .addComponent(we)))
        );
        tekstLayout.setVerticalGroup(
            tekstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(edytor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(tekstLayout.createSequentialGroup()
                .addComponent(we)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tekstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_cofnij)
                    .addComponent(wGórę))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(wy)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tekst", tekst);

        zasoby.setEnabled(false);
        zasoby.setFocusable(false);
        zasoby.setRequestFocusEnabled(false);

        jLabel3.setText("pokaż zasoby wg URI(tylko GET)");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        adresStrony.setText("https://isap.sejm.gov.pl");
        adresStrony.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        adresStrony.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adresStronyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 229, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 194, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel4);

        zasobyWczytaj.setText("wczytaj");
        zasobyWczytaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zasobyWczytajActionPerformed(evt);
            }
        });

        jButton3.setText("zachowaj razem");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("przywłaszcz");

        javax.swing.GroupLayout zasobyLayout = new javax.swing.GroupLayout(zasoby);
        zasoby.setLayout(zasobyLayout);
        zasobyLayout.setHorizontalGroup(
            zasobyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zasobyLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(zasobyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addGroup(zasobyLayout.createSequentialGroup()
                        .addComponent(adresStrony, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(zasobyWczytaj)))
                .addGap(0, 0, 0))
        );
        zasobyLayout.setVerticalGroup(
            zasobyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zasobyLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel3)
                .addGap(0, 0, 0)
                .addGroup(zasobyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adresStrony, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zasobyWczytaj))
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton3)
                .addGap(0, 0, 0)
                .addComponent(jButton4)
                .addGap(0, 0, 0))
        );

        jTabbedPane1.addTab("zasoby", zasoby);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void wGóręActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wGóręActionPerformed
        String s=wejście.getText();
        wejście.setText(wyjście.getText());
        wyjście.setText(s);
    }//GEN-LAST:event_wGóręActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void wstawIndywidualnieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wstawIndywidualnieActionPerformed
        wstawOffset.setEnabled(true);
        wstawOffset.setEditable(true);
    }//GEN-LAST:event_wstawIndywidualnieActionPerformed

    private void wstawPoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wstawPoActionPerformed
        wstawOffset.setEnabled(false);
    }//GEN-LAST:event_wstawPoActionPerformed

    private void wstawPrzedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wstawPrzedActionPerformed
        wstawOffset.setEnabled(false);
    }//GEN-LAST:event_wstawPrzedActionPerformed

    private void podstawKlikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_podstawKlikActionPerformed
        wyjście.setText(funkcje.podstaw(wejście.getText(),podstawCel.getText().split("\n"),podstawZmienne.getText().split("\n"),podstawWzór.getText().split("\n")));
    }//GEN-LAST:event_podstawKlikActionPerformed

    private void usuńKlikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuńKlikActionPerformed
        for(String s:cięcieUsuń.getText().split("\n"))
        wyjście.setText(wejście.getText().replaceAll(s,""));

    }//GEN-LAST:event_usuńKlikActionPerformed

    private void wyodrębnijKlikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wyodrębnijKlikActionPerformed
        wyjście.setText(funkcje.wyodrębnij(wejście.getText(),cięcieCel.getText().split("\n")));
    }//GEN-LAST:event_wyodrębnijKlikActionPerformed

    private void wstawOffsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wstawOffsetActionPerformed
        wstawOffset.setEnabled(true);
    }//GEN-LAST:event_wstawOffsetActionPerformed

    private void wstawKlikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wstawKlikActionPerformed
        wyjście.setText("DOMYŚLNIE USTAWIONO ŁĄCZENIE WIERSZY W JEDEN - PRZED SZUKANIEM\n\n\n\n\nWynik wstawiania:\n\n"
                +funkcje.wstaw(
                        wejście.getText()
                        ,wstawCel.getText().split("\n")
                        ,Pattern.MULTILINE
                        ,wstawWstawka.getText().split("\n")
                        ,wstawPrzed.isSelected()?0:(wstawPo.isSelected()?Integer.MAX_VALUE:Integer.parseInt(wstawOffset.getText()))
                        ,wstawPo.isSelected())
                );
    }//GEN-LAST:event_wstawKlikActionPerformed

    private void zamieńKlikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zamieńKlikActionPerformed

        wyjście.setText(funkcje.zamień(
            wejście.getText()
            ,zamieńCel.getText().split("\n")
            ,zamieńZamiennik.getText().split("\n")));
    }//GEN-LAST:event_zamieńKlikActionPerformed

    private void adresStronyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adresStronyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adresStronyActionPerformed

    private void zasobyWczytajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zasobyWczytajActionPerformed
        try {wyjście.setText("początek");
            URL u=new URL(adresStrony.getText());
            InputStreamReader isr=new InputStreamReader(u.openStream());
            BufferedReader br=new BufferedReader(isr);
            StringBuilder sb=new StringBuilder();
            while(br.ready()) wyjście.append(br.readLine());
            wyjście.append("koniec");
        }catch(IOException e){info.setText(e.getLocalizedMessage());}
    }//GEN-LAST:event_zasobyWczytajActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        super.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplikacja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aplikacja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane L1;
    private javax.swing.JScrollPane L2;
    private javax.swing.JScrollPane L3;
    private javax.swing.JScrollPane L4;
    private javax.swing.JScrollPane P1;
    private javax.swing.JScrollPane P2;
    private javax.swing.JScrollPane P3;
    private javax.swing.JScrollPane P4;
    private javax.swing.JScrollPane _4;
    private javax.swing.JButton _cofnij;
    private javax.swing.JTextField adresStrony;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextArea cięcieCel;
    private javax.swing.JTextArea cięcieUsuń;
    private javax.swing.JPanel edytor;
    private javax.swing.JScrollPane inf;
    private javax.swing.JTextArea info;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel numer1;
    private javax.swing.JLabel numer2;
    private javax.swing.JLabel numer3;
    private javax.swing.JLabel numer4;
    private javax.swing.JTextArea podstawCel;
    private javax.swing.JButton podstawKlik;
    private javax.swing.JTextArea podstawWzór;
    private javax.swing.JTextArea podstawZmienne;
    private javax.swing.JPanel tekst;
    private javax.swing.JButton usuńKlik;
    private javax.swing.JButton wGórę;
    private javax.swing.JScrollPane we;
    private javax.swing.JTextArea wejście;
    private javax.swing.JTextArea wstawCel;
    private javax.swing.JRadioButton wstawIndywidualnie;
    private javax.swing.JToggleButton wstawKlik;
    private javax.swing.JTextField wstawOffset;
    private javax.swing.JRadioButton wstawPo;
    private javax.swing.JRadioButton wstawPrzed;
    private javax.swing.JTextArea wstawWstawka;
    private javax.swing.JScrollPane wy;
    private javax.swing.JTextArea wyjście;
    private javax.swing.JButton wyodrębnijKlik;
    private javax.swing.JTextField wyodrębnij_NieaktywnyTekst;
    private javax.swing.JTextArea zamieńCel;
    private javax.swing.JButton zamieńKlik;
    private javax.swing.JTextArea zamieńZamiennik;
    private javax.swing.JPanel zasoby;
    private javax.swing.JButton zasobyWczytaj;
    // End of variables declaration//GEN-END:variables

    private void initDemo() {
        wejście.setText(CONSTANTS.DEMO_ListDoRzymian);
        
    }
}
